remote_theme: just-the-docs/just-the-docs@v0.7.0
title: The Red Book of MECCG
logo: "/assets/images/meccg.png"
favicon_ico: "/assets/images/TheRedBook.ico"
search_enabled: false
baseurl: "/"
permalink: pretty
heading_anchors: true
gh_edit_link: false
